services:
  - type: web
    name: financespro
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node -r dotenv/config server.js
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Esta variável precisa ser configurada manualmente no painel do Render
      - key: JWT_SECRET
        generateValue: true # Gera um valor aleatório seguro 